spring:
  config:
    import: classpath:/yigongil-private/application-dev.yml

  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.sql: debug

schedules:
  round-update: 0 0 0 * * *

oauth2:
  github:
    client:
      id: github-client-id
      secret: github-secret
      github-login-uri: https://github.com/login/oauth/authorize
    provider:
      token-uri: http://localhost:8080/fakeToken
      user-info-uri: http://localhost:8080/fakeInfo

jwt:
  expiration: 60
  key: qkljwnqdjnqjkdnqdwkdkm31i4j1dasksmd

