spring:
  profiles:
    active: dev
  config:
    import: classpath:yigongil-private/application-dev.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.sql: debug
