name: backend-test-on-pull-request
on:
  pull_request:
    branches: 
      - BE/develop
      - BE/release
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: ./backend
    
permissions:
  checks: write
  pull-requests: write
  
jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3
    
    - name: JDK17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle에 권한부여
      run: chmod +x gradlew
      
    - name: Test 실행
      run: ./gradlew build
      
    - name: Test 결과를 PR에 코멘트로 등록
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/build/test-results/test/TEST-*.xml'
  
        
      
        
        
